# Generated by Django 5.1.6 on 2025-04-01 09:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="readreceipt",
            name="message",
        ),
        migrations.AlterUniqueTogether(
            name="readreceipt",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="readreceipt",
            name="user",
        ),
        migrations.AlterModelOptions(
            name="chatroom",
            options={},
        ),
        migrations.RenameField(
            model_name="chatroom",
            old_name="created_at",
            new_name="created",
        ),
        migrations.RenameField(
            model_name="chatroom",
            old_name="users",
            new_name="members",
        ),
        migrations.RemoveField(
            model_name="chatroom",
            name="is_group",
        ),
        migrations.RemoveField(
            model_name="chatroom",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="chatroom",
            name="create_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="user_chatrooms",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="chatroom",
            name="type",
            field=models.CharField(
                choices=[("D", "Direct Room"), ("G", "Group")],
                default="D",
                max_length=5,
            ),
        ),
        migrations.AlterField(
            model_name="chatroom",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="chatroom",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name="ChannelDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("channel_name", models.CharField(max_length=255)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField(max_length=1000)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "room",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="chat.chatroom",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Message",
        ),
        migrations.DeleteModel(
            name="ReadReceipt",
        ),
    ]
