# Generated by Django 5.2 on 2025-04-04 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habit", "0001_initial"),
        ("notification", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notification",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="notification",
            name="habit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="habit.habit",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("task", "Task Notification"),
                    ("habit", "Habit Notification"),
                    ("system", "System Notification"),
                ],
                default="system",
                max_length=10,
            ),
        ),
    ]
