# Generated by Django 5.1.7 on 2025-03-31 06:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PomodoroSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('focus_time', models.IntegerField(help_text='Focus time in minutes')),
                ('break_time', models.IntegerField(help_text='Break time in minutes')),
                ('long_break_time', models.IntegerField(help_text='Long break time in minutes')),
                ('cycles', models.IntegerField(help_text='Number of cycles before long break')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('date', models.DateField()),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pomodoro_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pomodoro Session',
                'verbose_name_plural': 'Pomodoro Sessions',
                'ordering': ['-start_time'],
            },
        ),
    ]
