# Generated by Django 5.1.7 on 2025-03-31 08:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pomodoro', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='pomodorosession',
            constraint=models.UniqueConstraint(fields=('user', 'start_time'), name='unique_user_session'),
        ),
    ]
